name: WEbook CI & Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            backend/package.json
            frontend/package.json

      - name: Install & Test Backend
        run: |
          cd backend
          npm install
          npm run seed || true

      - name: Install & Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
